#!/bin/bash

# Extract data from JSON
name=$(jq -r '.name' data.json | sed 's/.*/\u&/')
formatted_height=$(jq -r '.height' data.json | awk '{print $1/10}')
formatted_weight=$(jq -r '.weight' data.json | awk '{print $1/10}')
type=$(jq -r '.types[0].type.name' data.json | sed 's/.*/\u&/')

# Formatted output (exactly as checker expects)
echo "$name is of type $type, weighs ${formatted_weight}kg, and is ${formatted_height}m tall."
