#!/bin/bash

# Extract data from JSON
name=$(jq -r '.name' data.json | sed 's/.*/\u&/')
height=$(jq -r '.height' data.json | awk '{print $1/10}')
weight=$(jq -r '.weight' data.json | awk '{print $1/10}')
type=$(jq -r '.types[0].type.name' data.json | sed 's/.*/\u&/')

# Format and print
echo "$name is of type $type, weighs ${weight}kg, and is ${height}m tall."
